spring:
  application:
    name: food-delivery

  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${POSTGRES_DB}'
    username: '${POSTRGRES_USER}'
    password: '${POSTRGRES_PASSWORD}'

  jpa:
    hibernate:
      ddl-auto: validate
